-- +goose Up
CREATE TABLE users (
	id integer primary key generated by default as identity,
	created_at timestamp not null,
	updated_at timestamp not null,
	name text not null unique
);


-- +goose Down
drop table users;
