-- +goose Up
CREATE TABLE feeds(
	id integer primary key generated by default as identity,
	created_at timestamp not null,
	updated_at timestamp not null,
	name text not null unique,
	url text not null unique,
	user_id integer not null references users on delete cascade

);


-- +goose Down
drop table feeds;
