-- +goose Up
CREATE TABLE feed_follows(
	id integer primary key generated by default as identity,
	created_at timestamp not null,
	updated_at timestamp not null,
	user_id integer references users(id) not null,
	feed_id integer references feeds(id) not null,
	unique(user_id, feed_id)
);


-- +goose Down
drop table feed_follows;
